#%RAML 1.0
title: RAML example 1

uses:
  codeGen: java-codegen-annotations.raml

types:
  Product:
    type: object
    (codeGen.javaClassType): interface
    (codeGen.javaClassName): Product
    (codeGen.javaPackageName): com.mutsys.exampleOne
    properties:
      name: string
      productId: integer
    