#%RAML 1.0
title: RAML example 1

annotationTypes:
  javaClassType:
    allowedTargets: TypeDeclaration
    type: string
    enum: ['interface','abstractClass','concreteClass']
  javaClassName:
    allowedTargets: TypeDeclaration
    type: string
  javaPackageName:
    allowedTargets: TypeDeclaration
    type: string

types:
  Product:
    type: object
    (javaClassType): interface
    (javaClassName): Product
    (javaPackageName): com.mutsys.foo
    properties:
      name: string
      productId: integer
    