#%RAML 1.0
title: RAML example 4

uses:
  codeGen: java-codegen-annotations.raml

types:
  Foo:
    (codeGen.javaClassType): interface
    (codeGen.javaClassName): Foo
    (codeGen.javaPackageName): com.mutsys.exampleFour
    type: object
    properties:
      code:
        type: string
      name:
        type: string


/things:
  (codeGen.javaClassType): interface
  (codeGen.javaClassName): ThingResource
  (codeGen.javaPackageName): com.mutsys.exampleFour.resource
  get:
    responses:
      200:
        body:
          application/json:
            type: Foo[]
  post:
    body:
      application/json:
        type: Foo
    responses:
      201:
        body:
          application/json:
            type: Foo
  /{code}:
    uriParameters:
      code:
        type: string
    get:
      responses:
        200:
          body:
            application/json:
              type: Foo
    put:
      body:
        application/json:
          type: Foo
      responses:
        200:
          body:
            application/json:
              type: Foo
    delete:
      responses:
        204:
